apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ .Values.airflow.env.airflowUser | b64enc }}
  password: {{ .Values.airflow.env.airflowPassword | b64enc }}