########################################
## CONFIG | Airflow Configs
## https://github.com/bitnami/containers/tree/main/bitnami/airflow#configuration
########################################

config:
  aesKey: movsb33mAGj9QyuCKGW/2PA2AgkYisCaplPjf5ecGXo=
  release:
    helmName: test-airflow
    helmNamespace: test-airflow
  namespace: test-airflow
  loadExample: "FALSE"
  executor: KubernetesExecutor
  parallelism: 1
  fernetKey: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
  image:
    repository: cartertsai/airflow-test-all
    tag: 1.0.6
  db:
    host: metadata
    port: 5432
    dbName: airflow
    dbUser: airflow
    dbPw: airflow

  airflowLogs:
    storageClassName: crc-csi-hostpath-provisioner
  airflowDags:
    storageClassName: crc-csi-hostpath-provisioner
  sparkDags:
    storageClassName: crc-csi-hostpath-provisioner
  metadata:
    storageClassName: crc-csi-hostpath-provisioner

airflow:
  replicas: 1
  image:
    # registry: hub.docker.com
    repository: cartertsai/airflow-test-all
    tag: 1.0.6
    pullPolicy: IfNotPresent
    uid: 1000650000
    gid: 0

  env:
    executor: KubernetesExecutor
    fernetKey: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    secretKey: a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
    airflowEmail: hamming0324@gamil.com
    airflowPassword: user
    airflowUser: user
    spark_home: /spark

metadata:
  ## if the `stable/postgresql` chart is used
  ## - [WARNING] the embedded Postgres is NOT SUITABLE for production deployments of Airflow
  ## - [WARNING] consider using an external database with `externalDatabase.*`
  ## - set to `false` if using `externalDatabase.*`
  ##
  name: metadata
  enabled: true
  image:
    # registry: hub.docker.com
    repository: bitnami/postgresql
    tag: 15.4.0
    pullPolicy: IfNotPresent
  
  securityContext:
    uid: 1000650000
    gid: 0

spark:
  enabled: false