apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-pods-permissions
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: airflow
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: ["","extensions","apps" ]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]

