apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-pods-rolebinding
  namespace:  {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: airflow
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: task-pods-permissions
subjects:
  - kind: ServiceAccount
    name: task-pods-serviceaccount
    namespace:  {{ .Release.Namespace }}