apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:         # Pod level
        runAsUser: {{ .Values.postgres.securityContext.uid }}
      containers:
        - name: postgres
          {{- include "postgres.image" . | indent 10 }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgredb
          securityContext:         # Pod level
            runAsUser: {{ .Values.postgres.securityContext.uid }}
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    app.kubernetes.io/managed-by: Helm
data:
  POSTGRES_DB: {{ .Values.config.db.dbName }}
  POSTGRES_USER: {{ .Values.config.db.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.config.db.dbPw }}
