---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pv-claim
  namespace:  {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: airflow-logs
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.config.airflowLogs.storageClassName }}
  storageClassName: {{ .Values.config.airflowLogs.storageClassName}}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  {{- if .Values.config.airflowDags.storageClassName }}
  storageClassName: {{ .Values.config.airflowDags.storageClassName}}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-dags-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  {{- if .Values.config.sparkDags.storageClassName }}
  storageClassName: {{ .Values.config.sparkDags.storageClassName}}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-pv-claim
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: metadata
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  {{- if .Values.config.metadata.storageClassName }}
  storageClassName: {{ .Values.config.metadata.storageClassName}}
  {{- end }}