apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.metadata.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      securityContext:         # Pod level
        runAsUser: {{ .Values.metadata.securityContext.uid }}
      containers:
        - name: {{ .Values.metadata.name }}
          {{- include "metadata.image" . | indent 10 }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.metadata.name }}-config
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: {{ .Values.metadata.name }}db
          securityContext:         # Pod level
            runAsUser: {{ .Values.metadata.securityContext.uid }}
      volumes:
        - name: {{ .Values.metadata.name }}db
          persistentVolumeClaim:
            claimName: {{ .Values.metadata.name }}-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.name }}-config
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.name }}
    app.kubernetes.io/managed-by: Helm
data:
  POSTGRES_DB: {{ .Values.config.db.dbName }}
  POSTGRES_USER: {{ .Values.config.db.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.config.db.dbPw }}
