apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-pods-serviceaccount
  namespace:  {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: airflow
    app.kubernetes.io/managed-by: Helm